# Generated by Django 4.0.3 on 2022-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image1',
            field=models.ImageField(default=None, upload_to='houses/%Y/%m'),
        ),
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(default=None, upload_to='houses/%Y/%m'),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(default=None, upload_to='houses/%Y/%m'),
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.ImageField(default=None, upload_to='houses/%Y/%m'),
        ),
    ]
