# Generated by Django 4.0.3 on 2022-03-18 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_house_image1_house_image2_house_image3_house_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='HostRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_identification', models.ImageField(default=None, upload_to='identification/%Y/%m')),
                ('after_identification', models.ImageField(default=None, upload_to='identification/%Y/%m')),
                ('description', models.TextField(blank=True, null=True)),
                ('delete_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
